### ISSUE TITLE
Add to OTIO and Shotcut? (not an issue, but rather a quick thought)

### ISSUE THREAD

**Issue by tin2tin** [apetrynet/otio-mlt-adapter#2]
Does Dan of Shotcut(&MLT) know about this adapter? He has OTIO on his Shotcut roadmap: https://shotcut.org/roadmap/ I guess if this adaptor is added to the official OTIO package, it would make implementing OTIO in Shotcut a simple thing for him?

**Comment by apetrynet** [comment]
Hi @tin2tin ! 
I think Dan knows of this, yes. He followed the initial PR that was linked to OTIO. I think he wanted to wait for the C++ port to mature before implementing. 
When it comes to adding this as an official adapter, the plan for OTIO adapters is actually to split them up into their own repos/packages like this. That way the adapters won't hold the main OTIO code back if the maintainers of adapters aren't actively monitoring the progress.
